# Generated by Django 5.1.4 on 2024-12-30 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='festival',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='category',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='lily.eventcategory'),
            preserve_default=False,
        ),
    ]
