# Generated by Django 5.1.4 on 2025-01-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lily', '0002_eventcategory_festival_slug_festival_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='category',
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
        migrations.DeleteModel(
            name='Festival',
        ),
    ]
